insert into estado values (11,'Rondônia','RO','N',52,'11RO','Porto Velho');
insert into estado values (12,'Acre','AC','N',22,'12AC','Rio Branco');
insert into estado values (13,'Amazonas','AM','N',62,'13AM','Manaus');
insert into estado values (14,'Roraima','RR','N',15,'14RR','Boa Vista');
insert into estado values (15,'Pará','PA','N',144,'15PA','Belém');
insert into estado values (16,'Amapá','AP','N',16,'16AP','Macapá');
insert into estado values (17,'Tocantins','TO','N',139,'17TO','Palmas');
insert into estado values (21,'Maranhão','MA','NE',217,'21MA','São Luís');
insert into estado values (22,'Piauí','PI','NE',224,'22PI','Teresina');
insert into estado values (23,'Ceará','CE','NE',184,'23CE','Fortaleza');
insert into estado values (24,'Rio Grande do Norte','RN','NE',167,'24RN','Natal');
insert into estado values (25,'Paraíba','PB','NE',223,'25PB','João Pessoa');
insert into estado values (26,'Pernambuco','PE','NE',185,'26PE','Recife');
insert into estado values (27,'Alagoas','AL','NE',102,'27AL','Maceió');
insert into estado values (28,'Sergipe','SE','NE',75,'28SE','Aracaju');
insert into estado values (29,'Bahia','BA','NE',417,'29BA','Salvador');
insert into estado values (31,'Minas Gerais','MG','SE',853,'31MG','Belo Horizonte');
insert into estado values (32,'Espírito Santo','ES','SE',78,'32ES','Vitória');
insert into estado values (33,'Rio de Janeiro','RJ','SE',92,'33RJ','Rio de Janeiro');
insert into estado values (35,'São Paulo','SP','SE',645,'35SP','São Paulo');
insert into estado values (41,'Paraná','PR','SE',399,'41PR','Curitiba');
insert into estado values (42,'Santa Catarina','SC','SE',295,'42SC','Florianópolis');
insert into estado values (43,'Rio Grande do Sul','RS','SE',497,'43RS','Porto Alegre');
insert into estado values (50,'Mato Grosso do Sul','MS','CO',79,'50MS','Campo Grande');
insert into estado values (51,'Mato Grosso','MT','CO',141,'51MT','Cuiabá');
insert into estado values (52,'Goiás','GO','CO',246,'52GO','Goiânia');
insert into estado values (53,'Distrito Federal','DF','CO',1,'53DF','Brasília');
